module.exports = {
    COMUNITY_CHAT: "COMUNITY_CHAT",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    USER_CONNECTED: "USER_CONNECTED",
    VERIFY_USER: "VERIFY_USER",
    TYPING: "TYPING",
    LOGOUT: "LOGOUT"
}